In [32]:
import pandas as pd
import json


df = pd.json_normalize(my_dict['features'])
df

,id,type,properties.WID,properties.Value1,properties.Value2,properties.Value3,geometry.type,geometry.coordinates
0,0,Feature,123,100,3,500,Point,"[-83.6514, 32.0177]"
1,1,Feature,456,200,2,600,Point,"[-83.6641, 32.0246]"
2,2,Feature,789,300,3,600,Point,"[-83.6143, 32.0213]"
3,3,Feature,987,200,1,300,Point,"[-83.6120649, 32.0380697]"

In [24]:
my_dict = {'type': 'FeatureCollection',
 'features': [{'id': '0',
   'type': 'Feature',
   'properties': {'WID': 123, 'Value1': 100, 'Value2': 3, 'Value3': 500},
   'geometry': {'type': 'Point', 'coordinates': [-83.6514, 32.0177]}},
  {'id': '1',
   'type': 'Feature',
   'properties': {'WID': 456, 'Value1': 200, 'Value2': 2, 'Value3': 600},
   'geometry': {'type': 'Point', 'coordinates': [-83.6641, 32.0246]}},
  {'id': '2',
   'type': 'Feature',
   'properties': {'WID': 789, 'Value1': 300, 'Value2': 3, 'Value3': 600},
   'geometry': {'type': 'Point', 'coordinates': [-83.6143, 32.0213]}},
  {'id': '3',
   'type': 'Feature',
   'properties': {'WID': 987, 'Value1': 200, 'Value2': 1, 'Value3': 300},
   'geometry': {'type': 'Point', 'coordinates': [-83.6120649, 32.0380697]}}]}